name: CI.yml
on:
  workflow_checkout:
  pull_request: 
    branches:
      - main
    push
      branches:
        - main

jobs:
  build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Bygg
      uses: actions/checkout@v07
        with:
          run: dotnet-version-10.0.x
          run: dotnet restore
          run: dotnet build --no-restore --configuration Release
    steps:
    - name: Testa
      uses: actions/setup-dotnet@v7.0.x
        with: 
          run: dotnet-version-10.0.x
          run: dotnet test --no build --configuration Release